# Database Configuration (Must match docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:db11}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port (Must match SERVER_PORT in docker-compose.yml)
server.port=8090

# JWT Configuration
demo.app.jwtCookieName=cnc-cookies
demo.app.jwtSecret=${JWT_SECRET}
demo.app.jwtExpirationMs=86400000
demo.app.jwtRefreshExpirationMs=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.admin.notification-emails=${ADMIN_EMAILS}

# AWS S3 Configuration
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-1
aws.bucketName=${AWS_BUCKET_NAME}

# Logging Configuration
logging.level.org.springframework.security=DEBUG
spring.jpa.open-in-view=false

# Activate logs
logging.level.org.hibernate.SQL=DEBUG

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

# Actuator and Prometheus Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
