

# Database Configuration (Must match docker-compose.yml)
spring.datasource.url=jdbc:postgresql://localhost:5432/db1
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port (Must match SERVER_PORT in docker-compose.yml)
server.port=8090

# jwt configuration

# JWT Configuration
demo.app.jwtCookieName=cnc-cookies
demo.app.jwtSecret=qFVFzWHpdEWBMjAwp9oZtvAqm122OWyv2cCu87cN0YArqJk1Z1kukGmOJkX9deBU43WyzWhvRegYNQrj7mQmj5
demo.app.jwtExpirationMs=86400000
demo.app.jwtRefreshExpirationMs=86400000



# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bakkalidouae75@gmail.com
spring.mail.password=admprzyyczhskkhy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.admin.notification-emails=P138324714@um5.ac.ma,bakkalisalma574@gmail.com


# AWS S3 Configuration
aws.accessKeyId=AKIAVRGZUA63XMDEZCAU
aws.secretAccessKey=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
aws.region=us-east-1
aws.bucketName=astrolearn-s3bucket



# Logging Configuration
logging.level.org.springframework.security=DEBUG
spring.jpa.open-in-view=false

# Activate logs
logging.level.org.hibernate.SQL=DEBUG

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

# Actuator and Prometheus Configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true