[frontend]
10.0.0.254 ansible_host=52.90.146.172 ansible_user=ec2-user

[backend]
10.0.1.85 ansible_host=34.234.211.41 ansible_user=ec2-user

[all:vars]
ansible_ssh_private_key_file=./ansible/ssh_key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
